### ISSUE TITLE
Create imaging dataset command should set `UseAllTableInfoInLoadAsFieldMap ` in the Pipeline it creates

### ISSUE THREAD

**Issue by tznind** [HicServices/RdmpDicom#118]
```
Error getting Tag 'Unknown' item.ValueRepresentation is (IS) Problem File:

<path to a bad dicom file>

An item with the same key has already been added. Key: Unknown

   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Rdmp.Dicom.PipelineComponents.DicomSources.DicomSource.ProcessDataset(String filename, DicomDataset ds, DataTable dt, IDataLoadEventListener listener, Dictionary`2 otherValuesToStoreInRow)

```

**Comment by tznind** [comment]
Use `UseAllTableInfoInLoadAsFieldMap`
